### ISSUE TITLE
Files too big to upload to Github

### ISSUE THREAD

**Issue by Ellior2** [Ellior2/Fish-546-Bioinformatics#2]
I have 16 raw files I wanted to upload to GitHub. I tried to compress one of them which reduced the size from 0.98GB to 755mb but the maximum size GitHub will allow is 25mb. Suggestions? @sr320

**Comment by sr320** [comment]
All big files have to go on owl, and linked to.
Will get that set up next week.

see also #1 - You should start out with this fasta annotation- this should fit on GitHub - I am pretty sure the limit is 100mb.
